Feature/auth to develop
SinaGram-DSM/Yally-iOS pull request #5
Opened 2021-01-22 07:39 UTC by Ga-yo

Feat : auth

Feat : pull conflict

Update : splash view img

Fix : pin code

Fix : accessToken

Fix : password rules

Fix : 예외처리

Fix : navigation title

Fix : 잘못된 api 고치기

Delete : AppDelegate

Fix : UI 예외처리

Feat : mainCell UI

Feat : maincell clean

Feat : YallyFilter

Fix : convenience init, naming

Fix : func naming

setupErrorMessage to textFieldErrorMessage

Add : private init

Move : YallyFilter

Rename : HttpResult, api, ok1

Fix : whildCard Delete

Add : final class

Fix : strong to weak self

Remove : setupUI

Fix : change rename, unowned self

Fix : postConfirmCode

Fix : Auth UI

Add : project.pbxproj

2021-01-23 12:20 UTC, DAEUN28 requested changes
저번에 언급했던 내용 중 final 키워드 적용, private 키워드 적용, 필요없는 self 키워드 사용 자제 는 아직도 코드에 남아있네요...ㅠ
그리고 PR은 새로 생성하지말고 작업하던 브랜치에서 계속 푸쉬하면 됩니다.
코멘트 남긴 부분 확인하고 수정 후 수정했으니 확인해달라는 코멘트 남겨주세요.
제가 남긴 코멘트에 대해 할 이야기가 있다면 해당 코멘트에서 계속 의견 추가하면 됩니다 :)

2021-01-23 12:20 UTC, DAEUN28 commented on Yally/Yally/Source/Networking/HTTPClient.swift
> +                           headers: url.headers())
중복코드가 너무 많은 것 같아요.
http method만 다르고 같은 역할을 하는 메서드가 여러 개 있는 건 비효율적인 것 같습니다.
인코딩방식이 다른 것도 아니구 차라리 http method를 매개변수로 받는게 나을 것 같아요.

2021-01-23 12:20 UTC, DAEUN28 commented on Yally/Yally/Source/View/MainTableViewCell.swift
> +    @IBOutlet weak var doComment: UIButton!
접미사에 button을 붙이지 않은 이유가 있을까요? 
그리고 저번리뷰에서 언급했던 것처럼 외부 접근이 필요없는 코드는 private 키워드를 사용해 은닉화하는게 좋아용

2021-01-23 12:20 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/Auth/SplashViewController.swift
> +    @IBOutlet weak var SignBtn: UIButton!
프로퍼티에 대문자 카멜케이스라니?????

2021-01-23 14:09 UTC, Ga-yo commented on Yally/Yally/Source/ViewController/Auth/SplashViewController.swift
> +    @IBOutlet weak var SignBtn: UIButton!
수정했습니다 :)

2021-01-23 14:13 UTC, Ga-yo commented on Yally/Yally/Source/ViewController/Auth/SplashViewController.swift
> +    @IBOutlet weak var SignBtn: UIButton!
그리고 외부 접근이 필요없는 코드는 private로 변경하였습니다..!

2021-01-23 14:16 UTC, Ga-yo commented on Yally/Yally/Source/Networking/HTTPClient.swift
> +                           headers: url.headers())
이 부분에 대해서 저도 생각을 해봤는데 지수랑 겹쳐있는 부분이라서 머지 이후에 한꺼번에 고칠려고 합니다..!

2021-01-24 01:46 UTC, DAEUN28 approved these changes

2021-01-25 14:26 UTC, Ga-yo commented on Yally/Yally/Source/ViewController/Auth/SplashViewController.swift
> +    @IBOutlet weak var SignBtn: UIButton!
final 키워드도 적용하였습니다!

2021-01-25 14:35 UTC, Ga-yo commented on Yally/Yally/Source/ViewController/Auth/SplashViewController.swift
> +    @IBOutlet weak var SignBtn: UIButton!
self 사용 자제도 적용했습니다!

2021-01-26 11:03 UTC, DAEUN28 commented
@Ga-yo approve되면 merge하면 됩니당

2021-01-27 02:44 UTC, merged