feature/timeLine to develop
SinaGram-DSM/Yally-iOS pull request #6
Opened 2021-02-01 13:50 UTC by Ga-yo

2021-02-02 11:40 UTC, DAEUN28 requested changes
일단 커밋단위가 너무커서 리뷰어에게 너무 많은 부담이 됩니다ㅠ
Squash한건가요? Squash한거라면 PR 리뷰 후 하는게 맞습니다ㅠㅠ 다음부터는 리뷰가 끝난 후 Squash 진행해주세요.

1. 중복코드가 너무 많습니다. Rx의 메서드를 사용해 의미없는 코드를 줄이면 좋을 것 같아요. 그리고 스위프트의 기능을 더 잘 활용하면 중복코드를 줄일 수 있습니다 :)
2. 저번 #4 PR에서도 언급한 내용이 곳곳에 빠져있네요. 다음과 같은 기본적인 내용은 다음부터 리뷰에서 제외할게요. 의식적으로 기본적인 내용을 지키려고 해보면 좋을 것 같아요.
- 강한참조
- 네이밍 컨벤션(타입은 대문자 카멜케이스, 프로퍼티 및 메서드 명은 소문자 카멜케이스 등)

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/Model/MainModel.swift
> +struct posts: Codable {
타입은 대문자 카멜케이스를 권장합니다~

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/Networking/HTTPClient.swift
> +    func get(_ url: YallyURL, params: [String:Any]?) -> HTTPResult {
`func get(_ url: YallyURL, params: [String: Any]? = nil) -> HTTPResult`
와 같이 파라미터에 기본값을 설정하면 더 깔끔한 코드가 될 수 있어요 👍

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/Networking/TimeLineAPI.swift
> +                        multipartFormData.append(value.data(using: String.Encoding.utf8)!, withName: key)
compactMap을 사용하면 더 좋은 코드가 될 수 있을 것 같아요~!

```swift
arrayObj.compactMap { ($0 as? String).data(using: .utf8) }
  .forEach {
    multipartFormData.append($0, withName: key)
  }
```

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/VIewModel/DetailViewModel.swift
> +    static let detailData = PublishRelay<[DetailModel]>()
static으로 선언한 이유가 있을까요?

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/VIewModel/DetailViewModel.swift
> +                    model.removeAll()
model 변수를 사용하는 이유가 있을까요?

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/VIewModel/DetailViewModel.swift
> +            }).disposed(by: self.disposeBag)
강한참조는 강한순환참조를 일으킬 수 있어요 😱

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/VIewModel/MainViewModel.swift
> +            api.getTimeLine(1).subscribe(onNext: { response, statusCode in
flatMap을 사용하면 더 깔끔한 코드가 될 것 같아요 :)

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/View/InputTextField.swift
> +    let commentTextView: UITextView = {
then이라는 라이브러리를 한 번 찾아보면 좋을 것 같아요 👍

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/View/MainTableViewCell.swift
> +                popupTitle.isHidden = false
if 문을 사용하지 않고도 작성할 수 있는 코드네요 👍

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/View/MainTableViewCell.swift
> +                timeLabel.isHiddenAnimated(value: !backImageBtn.isSelected, duration: 0.5)
중복코드가 너무 많아요ㅠ backImageBtn.alpha 프로퍼티의 경우 삼항 연산자를 사용하고, 나머지는 통합하면 3줄이면 충분한 코드네요 😢

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/DetailViewController.swift
> +                    deleteText.accept(())
bind 메서드를 활용하면 좋을 것 같아요~!

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/DetailViewController.swift
> +            commentTableView.reloadData()
위의 postComment와 옵저버블을 합치면 중복코드를 없앨 수 있을 것 같아요 👍

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/DetailViewController.swift
> +    func getFileURL() -> URL {
이런건 계산 프로퍼티로 만들면 좋을 것 같아요

2021-02-02 11:40 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/MainViewController.swift
> +            cell.backImageBtn.load(url: repository.img!)
하나하나 설정하지말고 cell에 메서드를 하나만들면 깔끔하겠쥬?

2021-02-03 08:57 UTC, Ga-yo commented on Yally/Yally/Source/ViewController/TimeLine/DetailViewController.swift
> +                    deleteText.accept(())
그러면 전체적으로 subscribe 대신 bind를 활용하는게 좋을까요? 둘이 에러컨트롤을 할 수 있나 없냐의 차이인 것 같은데..

2021-02-03 09:10 UTC, Ga-yo commented on Yally/Yally/Source/VIewModel/MainViewModel.swift
> +            api.getTimeLine(1).subscribe(onNext: { response, statusCode in
flatMap을 어떻게 써야할지 감이 안옵니다,,ㅜ api 요청을 subscribe하는 부분에 적용해야하나요?..?..?

2021-02-03 09:12 UTC, Ga-yo commented
앗 Squash 먼저 해야되는줄알고..! 다음부터는 주의하겠습니답!

2021-02-03 12:09 UTC, DAEUN28 commented on Yally/Yally/Source/VIewModel/MainViewModel.swift
> +            api.getTimeLine(1).subscribe(onNext: { response, statusCode in
이런식으로 데이터의 흐름을 변경할 수 있어용

```swift
input.loadData.asObservable
  .flatMap { api.getTimeLine }
  .subscribe {
```

2021-02-03 12:13 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/DetailViewController.swift
> +                    deleteText.accept(())
그 bind 메서드가 아니라 이런식으로 활용할 수 있는 bind 메서드를 의도했어요 :)
```swift
cell.popupTitle.rx.tap.bind(to: deleteText).disposed(by: cell.disposeBag)
```

2021-02-03 12:48 UTC, Ga-yo commented on Yally/Yally/Source/VIewModel/DetailViewModel.swift
> +    static let detailData = PublishRelay<[DetailModel]>()
뷰컨에서도 데이터를 받을걸 생각해서 static으로 선언을 해줬었습니다 ,, 근데 생각해보니 output으로 response 값을 넘겨줘도 괜찮을것같아요...!

2021-02-04 06:04 UTC, Ga-yo commented on Yally/Yally/Source/VIewModel/MainViewModel.swift
> +            api.getTimeLine(1).subscribe(onNext: { response, statusCode in
withLatestFrom 이게 붙은 경우에도 flatMap으로 변경할 수가 있나요??

2021-02-04 11:36 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/DetailViewController.swift
> +            if !isRecord.value {
CommentTextField 프로퍼티와 ModifyCommentTyping 메서드는 왜 대문자 카멜케이스를 사용하나요?

2021-02-04 11:39 UTC, DAEUN28 reviewed
언급한 부분이 아니더라도 전체 코드에서 제가 남긴 피드백에 해당되는 코드는 수정하는게 좋을 것 같아요 :)
동작하는 것이 가장 중요하지만 제대로 동작하는 것만큼 깔끔한 코드도 중요해요~!

2021-02-04 11:39 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/PostViewController.swift
> +            timeLabel.isHidden = !isRecord.value ? false : true
isRecord.value 값 자체가 bool 값아닌가요? 삼항연산자를 사용하는 이유가 있을까요?

2021-02-04 12:14 UTC, DAEUN28 commented on Yally/Yally/Source/VIewModel/MainViewModel.swift
> +            api.getTimeLine(1).subscribe(onNext: { response, statusCode in
당연히 Observable이라면 뭐든지 flatMap을 사용해 데이터의 흐름을 변경할 수 있어요

2021-02-04 13:29 UTC, Ga-yo commented on Yally/Yally/Source/ViewController/TimeLine/DetailViewController.swift
> +            if !isRecord.value {
앗 실수입니다...

2021-02-04 13:42 UTC, Ga-yo commented on Yally/Yally/Source/ViewController/TimeLine/MainViewController.swift
> +            cell.backImageBtn.load(url: repository.img!)
음성파일을 다운받아서 그걸 컨트롤하는 부분도 cell안에서 처리가 가능할까요..? 해당 클래스 안에서 AVAudioPlayer로 선언해준 변수로 설정해야하는데 ,, cell 안에서 처리를 하면 컨트롤하기 힘들 것 같아서 고민하고 있습니다 ,,

2021-02-05 12:04 UTC, DAEUN28 commented
@Ga-yo 피드백 반영완료된건가요?

2021-02-08 01:44 UTC, Ga-yo commented
앗 아뇨 아직이요!

2021-02-08 03:15 UTC, Ga-yo commented
@DAEUN28 피드백 반영했습니다..!

2021-02-09 11:46 UTC, DAEUN28 commented on Yally/Yally/Source/ViewController/TimeLine/MainViewController.swift
> +            cell.backImageBtn.load(url: repository.img!)
옵저버블이나 클로저를 넘겨주면 되지 않을까요?

2021-02-09 12:06 UTC, DAEUN28 approved these changes

2021-02-09 13:25 UTC, merged